//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WizIns.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WizIns.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   한국하이테크과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _100 {
            get {
                return ResourceManager.GetString("100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   검사작업 중입니다. 종료하면 자료가 사라집니다. 그래도 종료하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _101 {
            get {
                return ResourceManager.GetString("101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   검사작업을 하지 않고선 절마감을 할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _102 {
            get {
                return ResourceManager.GetString("102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   라벨을 발행하지 않았습니다. 그래도 다음 검사를 하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _103 {
            get {
                return ResourceManager.GetString("103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   지금 종료하면 검사 자료가 사라집니다. 종료하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _104 {
            get {
                return ResourceManager.GetString("104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   초기화 하면 검사한 내역이 사라집니다. 초기화 하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _105 {
            get {
                return ResourceManager.GetString("105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Database Connection Fail !!!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _150 {
            get {
                return ResourceManager.GetString("150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   라벨 출력과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _160 {
            get {
                return ResourceManager.GetString("160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   검사 방법과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _161 {
            get {
                return ResourceManager.GetString("161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loss(봇방) 부여과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _162 {
            get {
                return ResourceManager.GetString("162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작업조과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _163 {
            get {
                return ResourceManager.GetString("163", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Windows 폴더에 Wizard.ini 파일이 존재하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _170 {
            get {
                return ResourceManager.GetString("170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   에러가 발생했습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _201 {
            get {
                return ResourceManager.GetString("201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택한 항목이 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _202 {
            get {
                return ResourceManager.GetString("202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수정/삭제 할 수 있는 항목이 아닙니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _203 {
            get {
                return ResourceManager.GetString("203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택하신 항목을 삭제하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _211 {
            get {
                return ResourceManager.GetString("211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   에러가 발생했습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _991 {
            get {
                return ResourceManager.GetString("991", resourceCulture);
            }
        }
        
        /// <summary>
        ///   에러번호 :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _992 {
            get {
                return ResourceManager.GetString("992", resourceCulture);
            }
        }
        
        /// <summary>
        ///   에러위치 :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _993 {
            get {
                return ResourceManager.GetString("993", resourceCulture);
            }
        }
        
        /// <summary>
        ///   에러설명 :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _994 {
            get {
                return ResourceManager.GetString("994", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로그램을 종료합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _995 {
            get {
                return ResourceManager.GetString("995", resourceCulture);
            }
        }
        
        /// <summary>
        ///   발행할 라벨이 선택되지 않았습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _996 {
            get {
                return ResourceManager.GetString("996", resourceCulture);
            }
        }
        
        /// <summary>
        ///   발행정보를 변경할 라벨이 선택되지 않았습닌다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _997 {
            get {
                return ResourceManager.GetString("997", resourceCulture);
            }
        }
        
        /// <summary>
        ///   불량입니다. 등록하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _998 {
            get {
                return ResourceManager.GetString("998", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재 진행중인 검사작업이 있습니다. 진행중인 작업을 종료하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _999 {
            get {
                return ResourceManager.GetString("999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_down {
            get {
                object obj = ResourceManager.GetObject("arrow_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_up {
            get {
                object obj = ResourceManager.GetObject("arrow_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap calendar {
            get {
                object obj = ResourceManager.GetObject("calendar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap calendar__1_ {
            get {
                object obj = ResourceManager.GetObject("calendar (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap calendar__2_ {
            get {
                object obj = ResourceManager.GetObject("calendar (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap delete_1 {
            get {
                object obj = ResourceManager.GetObject("delete_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_search_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-search-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_search_96 {
            get {
                object obj = ResourceManager.GetObject("icons8-search-96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap times {
            get {
                object obj = ResourceManager.GetObject("times", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
